# Generated by Django 4.0.5 on 2022-06-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='photo',
            field=models.ImageField(blank=True, default='avatars/user.png', upload_to='avatars/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, default='avatars/user.png', upload_to='avatars/', verbose_name='Фото'),
        ),
    ]
