# Generated by Django 4.0.4 on 2022-04-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_client_options_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
