# Generated by Django 4.0.4 on 2022-04-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBodywork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CarCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CarSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodywork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carbodywork')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carbrand')),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carcoverage')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carmodel')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carsalon')),
            ],
        ),
    ]
