# Generated by Django 4.0.5 on 2022-06-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_callapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callapplication',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
