# Generated by Django 4.0.4 on 2022-04-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(to='carwash.service'),
        ),
    ]
