# Generated by Django 4.0.4 on 2022-04-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0006_alter_order_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
    ]
