# Generated by Django 4.0.4 on 2022-05-03 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0009_alter_car_car_class'),
        ('carwash', '0008_order_is_payed_service_description_alter_price_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Авто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(to='carwash.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='price',
            name='car_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carclass', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='price',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
