# Generated by Django 4.0.5 on 2022-06-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='avatars/user.png', upload_to='avatars/', verbose_name='Фото'),
        ),
    ]
