# Generated by Django 4.0.4 on 2022-04-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_created_at_car_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='state_number',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
