# Generated by Django 4.0.4 on 2022-05-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carclass'),
        ),
    ]
