# Generated by Django 4.0.4 on 2022-05-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_car_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.carclass'),
            preserve_default=False,
        ),
    ]
